In [54]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [55]:
dataset = pd.read_csv(r"D:\DataScience\Study_Materials\Machine Learning\DATASET\Decision_Tree_Salaries_dataset.csv")

oe=OrdinalEncoder()

dataset[["company","job","degree"]]=oe.fit_transform(dataset[["company","job","degree"]])

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
dataset


company  job  degree  salary_more_then_100k
0       2.0  2.0     0.0                      0
1       2.0  2.0     1.0                      0
2       2.0  0.0     0.0                      1
3       2.0  0.0     1.0                      1
4       2.0  1.0     0.0                      0
5       2.0  1.0     1.0                      1
6       0.0  2.0     1.0                      0
7       0.0  1.0     0.0                      0
8       0.0  0.0     0.0                      0
9       0.0  0.0     1.0                      1
10      1.0  2.0     0.0                      1
11      1.0  2.0     1.0                      1
12      1.0  0.0     0.0                      1
13      1.0  0.0     1.0                      1
14      1.0  1.0     0.0                      1
15      1.0  1.0     1.0                      1

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [58]:
print(X_train)

[[1. 0. 1.]
 [2. 1. 0.]
 [2. 0. 0.]
 [1. 1. 0.]
 [1. 2. 0.]
 [0. 1. 0.]
 [1. 1. 1.]
 [1. 2. 1.]
 [2. 0. 1.]
 [2. 2. 0.]
 [2. 1. 1.]
 [1. 0. 0.]]


In [59]:
print(y_train)

[1 0 1 1 1 0 1 1 1 0 1 1]


In [60]:
print(X_test)

[[2. 2. 1.]
 [0. 2. 1.]
 [0. 0. 0.]
 [0. 0. 1.]]


In [61]:
print(y_test)

[0 0 0 1]


In [62]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [63]:
print(X_train)

[[-0.53452248 -1.20740686  1.18321596]
 [ 1.06904497  0.10976426 -0.84515425]
 [ 1.06904497 -1.20740686 -0.84515425]
 [-0.53452248  0.10976426 -0.84515425]
 [-0.53452248  1.42693538 -0.84515425]
 [-2.13808994  0.10976426 -0.84515425]
 [-0.53452248  0.10976426  1.18321596]
 [-0.53452248  1.42693538  1.18321596]
 [ 1.06904497 -1.20740686  1.18321596]
 [ 1.06904497  1.42693538 -0.84515425]
 [ 1.06904497  0.10976426  1.18321596]
 [-0.53452248 -1.20740686 -0.84515425]]


In [64]:
print(X_test)

[[ 1.06904497  1.42693538  1.18321596]
 [-2.13808994  1.42693538  1.18321596]
 [-2.13808994 -1.20740686 -0.84515425]
 [-2.13808994 -1.20740686  1.18321596]]


In [65]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 12, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=12)

In [66]:
classifier.predict(sc.transform([[2.0,1.0,0.0]]))

array([1], dtype=int64)

In [67]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 0]
 [1 0]
 [1 1]]


In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 3]
 [0 1]]


0.25

In [71]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2,x3 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 1),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 1),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 1))
plt.contourf(X1, X2,x3, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel(), x3.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN (Training set)')
plt.xlabel('job')
plt.ylabel('salary_more_then_100k')
plt.legend()
plt.show()

MemoryError: Unable to allocate 7.88 GiB for an array with shape (88176088, 12) and data type float64