## Importing Libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

## Importing Dataset

In [3]:
dataset = pd.read_csv(r"D:\DataScience\Study_Materials\Machine Learning\DATASET\Brain_Stroke_Prediction\full_data.csv")

#encoding values
oe=OrdinalEncoder()
dataset[["gender","ever_married","work_type","Residence_type","smoking_status"]]=oe.fit_transform(dataset[["gender","ever_married","work_type","Residence_type","smoking_status"]])

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
dataset

	

gender   age  hypertension  heart_disease  ever_married  work_type  \
0        1.0  67.0             0              1           1.0        1.0   
1        1.0  80.0             0              1           1.0        1.0   
2        0.0  49.0             0              0           1.0        1.0   
3        0.0  79.0             1              0           1.0        2.0   
4        1.0  81.0             0              0           1.0        1.0   
...      ...   ...           ...            ...           ...        ...   
4976     1.0  41.0             0              0           0.0        1.0   
4977     1.0  40.0             0              0           1.0        1.0   
4978     0.0  45.0             1              0           1.0        0.0   
4979     1.0  40.0             0              0           1.0        1.0   
4980     0.0  80.0             1              0           1.0        1.0   

      Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0                1.0             228.69  36.6             1.0       1  
1                0.0             105.92  32.5             2.0       1  
2                1.0             171.23  34.4             3.0       1  
3                0.0             174.12  24.0             2.0       1  
4                1.0             186.21  29.0             1.0       1  
...              ...                ...   ...             ...     ...  
4976             0.0              70.15  29.8             1.0       0  
4977             1.0             191.15  31.1             3.0       0  
4978             0.0              95.02  31.8             3.0       0  
4979             0.0              83.94  30.0             3.0       0  
4980             1.0              83.75  29.1             2.0       0  

[4981 rows x 11 columns]

## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
print(X_train)

[[  0.    26.     0.   ... 168.15  22.9    2.  ]
 [  0.    10.     0.   ...  57.28  15.4    2.  ]
 [  1.    10.     0.   ...  70.7   25.4    0.  ]
 ...
 [  0.    56.     0.   ... 224.63  42.8    2.  ]
 [  1.    57.     0.   ... 107.49  29.5    2.  ]
 [  0.     9.     0.   ...  90.22  18.7    0.  ]]


In [6]:
print(y_train)

[0 0 0 ... 0 0 0]


In [7]:
print(X_test)

[[  0.    40.     0.   ... 110.6   33.3    1.  ]
 [  0.    78.     0.   ... 234.06  33.7    2.  ]
 [  1.    14.     0.   ...  72.28  19.     0.  ]
 ...
 [  0.    80.     0.   ...  75.62  25.1    3.  ]
 [  1.    18.     0.   ...  83.37  24.4    0.  ]
 [  1.     2.     0.   ...  86.57  18.     0.  ]]


In [8]:
print(y_test)

[0 0 0 ... 0 0 0]


## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
print(X_train)

[[-0.85203898 -0.76992324 -0.32760168 ...  1.37219738 -0.8198263
   0.58661938]
 [-0.85203898 -1.47558671 -0.32760168 ... -1.07747037 -1.92339014
   0.58661938]
 [ 1.17365522 -1.47558671 -0.32760168 ... -0.78095606 -0.45197169
  -1.28445098]
 ...
 [-0.85203898  0.55319576 -0.32760168 ...  2.62012048  2.10829642
   0.58661938]
 [ 1.17365522  0.59729972 -0.32760168 ...  0.03191736  0.15130988
   0.58661938]
 [-0.85203898 -1.51969067 -0.32760168 ... -0.34966252 -1.43782205
  -1.28445098]]


In [11]:
print(X_test)

[[-0.85203898 -0.15246771 -0.32760168 ...  0.10063267  0.71044889
  -0.3489158 ]
 [-0.85203898  1.52348302 -0.32760168 ...  2.82847591  0.76930563
   0.58661938]
 [ 1.17365522 -1.29917084 -0.32760168 ... -0.74604603 -1.3936795
  -1.28445098]
 ...
 [-0.85203898  1.61169096 -0.32760168 ... -0.67224888 -0.49611424
   1.52215457]
 [ 1.17365522 -1.12275497 -0.32760168 ... -0.50101297 -0.59911353
  -1.28445098]
 [ 1.17365522 -1.82841844 -0.32760168 ... -0.43030911 -1.54082134
  -1.28445098]]


## Training the K-NN model on the Trainging Set

In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 71, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=71)

## Predicting New Result

In [13]:
classifier.predict(sc.transform([[1.0,67.0,0,1,1.0,1.0,1.0,228.69,36.6,1.0]]))

array([0], dtype=int64)

## Predicting the Test set Result

In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Marking the Confussion Matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1187    0]
 [  59    0]]


0.9526484751203852